### ISSUE TITLE
Implement Cell STS JWKS servers as sperate processes which can serve with SSL

### ISSUE THREAD

**Issue by hasinthaindrajee** [celleryio/mesh-security#53]
**Description:**
Currently JWKs endpoints serve traffic without SSL. Also they are a part of existing STS process. 

As a good practice we need to implement JWKS server as a separate process and also serve it through TLS as a way to trust bootstrap.

**Comment by hasinthaindrajee** [comment]
@tharindulak : Can we close this by pointing to the relevant implementation ?

**Comment by tharindulak** [comment]
Fixed by #64

**Comment by hasinthaindrajee** [comment]
@tharindulak : Can we close this ? If so can u please close this issue ?
